language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.5
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  directories:
    - node_modules
  yarn:
    - true

before_script:
  - yarn

script:
  - yarn test
